/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Windows;

import GameMechanics.Dice;
import GameMechanics.DiceJail;
import GameMechanics.DiceThrowed;
import GameMechanics.PlayersLoop;
import UI.Board;
import Viewer.Viewer;
import Viewer.ViewerInfoHandler;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author Michal
 */
public class GameWindow extends javax.swing.JPanel {

    private final Viewer ViewerBoard;
    private final Board board;

    public Board getBoard() {
        return board;
    }

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();

        ViewerBoard = new Viewer();
        ViewerBoard.setPreferredSize(new Dimension(1000, 1000));
        board = new Board(ViewerBoard);

        JPboard.setLayout(new BorderLayout());
        JPboard.add(ViewerBoard, BorderLayout.CENTER);
        JLabel infoLabel = new JLabel(" ");
        JPboard.add(infoLabel, BorderLayout.SOUTH);
        ViewerBoard.addMouseMotionListener(
                new ViewerInfoHandler(infoLabel, ViewerBoard));
        JPboard.setVisible(true);

        JTALog.setEditable(false);
    }

    public void TextLog(String msg) {
        if (msg.isEmpty()){
            return;
        }
        if (msg.endsWith("\n")) {
            JTALog.append(msg);
        } else {
            JTALog.append(msg + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPboard = new javax.swing.JPanel();
        JPMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTALog = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        JBThrow = new javax.swing.JButton();
        JBBuy = new javax.swing.JButton();
        JBEndTurn = new javax.swing.JButton();
        JBShowFieldInfo = new javax.swing.JButton();
        JBResetView = new javax.swing.JButton();

        JPboard.setPreferredSize(new java.awt.Dimension(498, 100));

        javax.swing.GroupLayout JPboardLayout = new javax.swing.GroupLayout(JPboard);
        JPboard.setLayout(JPboardLayout);
        JPboardLayout.setHorizontalGroup(
            JPboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        JPboardLayout.setVerticalGroup(
            JPboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JPMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(200, 32767));

        JTALog.setColumns(20);
        JTALog.setRows(5);
        JTALog.setMaximumSize(new java.awt.Dimension(140, 140));
        jScrollPane1.setViewportView(JTALog);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JBThrow.setText("Rzut koścmi");
        JBThrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBThrowActionPerformed(evt);
            }
        });

        JBBuy.setText("Kup");
        JBBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuyActionPerformed(evt);
            }
        });

        JBEndTurn.setText("Zakończ turę");
        JBEndTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEndTurnActionPerformed(evt);
            }
        });

        JBShowFieldInfo.setText("Pokarz kartę");
        JBShowFieldInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBShowFieldInfoActionPerformed(evt);
            }
        });

        JBResetView.setText("Plansza");
        JBResetView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBResetViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JBEndTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JBThrow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBBuy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBShowFieldInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBResetView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBThrow)
                    .addComponent(JBBuy)
                    .addComponent(JBShowFieldInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBEndTurn)
                    .addComponent(JBResetView))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPMenuLayout = new javax.swing.GroupLayout(JPMenu);
        JPMenu.setLayout(JPMenuLayout);
        JPMenuLayout.setHorizontalGroup(
            JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        JPMenuLayout.setVerticalGroup(
            JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPboard, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPboard, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
            .addComponent(JPMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBThrowActionPerformed
        int way;
        try {
            way = Dice.Throw();
        } catch (DiceThrowed ex) {
            TextLog(ex.getMessage());
            return;
        } catch (DiceJail ex) {
            TextLog(ex.getMessage());
            return;
            //todo go to Jail
        }
        if (Dice.getDice1() == Dice.getDice2()) {
            TextLog(String.format("Throwed %d and %d -> %d DUBEL!\n", Dice.getDice1(), Dice.getDice2(), way));
        } else {
            TextLog(String.format("Throwed %d and %d -> %d\n", Dice.getDice1(), Dice.getDice2(), way));
        }
        TextLog(PlayersLoop.getCurrentPlayer().Move(way));
        board.Repaint();
    }//GEN-LAST:event_JBThrowActionPerformed

    private void JBEndTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEndTurnActionPerformed
        if (!Dice.isThrowed()) {
            TextLog("You have to throw the dice\n");
            return;
        }
        PlayersLoop.iterator().next();
        TextLog(String.format("Current player %s (%d$)\n", PlayersLoop.getCurrentPlayer().toString(), PlayersLoop.getCurrentPlayer().GetMoney()));
        Dice.Reset();
    }//GEN-LAST:event_JBEndTurnActionPerformed

    private void JBResetViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBResetViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBResetViewActionPerformed

    private void JBBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBBuyActionPerformed

    private void JBShowFieldInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBShowFieldInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBShowFieldInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuy;
    private javax.swing.JButton JBEndTurn;
    private javax.swing.JButton JBResetView;
    private javax.swing.JButton JBShowFieldInfo;
    private javax.swing.JButton JBThrow;
    private javax.swing.JPanel JPMenu;
    private javax.swing.JPanel JPboard;
    private javax.swing.JTextArea JTALog;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
